title: Hello world!
author: Molly Liu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Test site for GitHub Pages Learning Lab

# social links
twitter_username: mozliu
github_username: mozliu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
